//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPISAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AREA_PERSONAL
    {
        public AREA_PERSONAL()
        {
            this.DPERSONALES = new HashSet<DPERSONALES>();
        }
    
        public string COD_AREA_PERSONAL { get; set; }
        public string DES_AREA_PERSONAL { get; set; }
    
        public virtual ICollection<DPERSONALES> DPERSONALES { get; set; }
    }
}
