//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPISAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASE_ESPECIALIDAD
    {
        public CLASE_ESPECIALIDAD()
        {
            this.DFORMACIONs = new HashSet<DFORMACION>();
        }
    
        public string COD_CLASE { get; set; }
        public string COD_ESPECIALIDAD { get; set; }
        public string DES_ESPECIALIDAD { get; set; }
    
        public virtual CLASE_INSTITUTO CLASE_INSTITUTO { get; set; }
        public virtual ICollection<DFORMACION> DFORMACIONs { get; set; }
    }
}
