//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPISAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASE_INSTITUTO
    {
        public CLASE_INSTITUTO()
        {
            this.CLASE_ESPECIALIDAD = new HashSet<CLASE_ESPECIALIDAD>();
            this.CLASE_TITULO = new HashSet<CLASE_TITULO>();
            this.DFORMACIONs = new HashSet<DFORMACION>();
        }
    
        public string COD_CLASE { get; set; }
        public string DES_CLASE { get; set; }
    
        public virtual ICollection<CLASE_ESPECIALIDAD> CLASE_ESPECIALIDAD { get; set; }
        public virtual ICollection<CLASE_TITULO> CLASE_TITULO { get; set; }
        public virtual ICollection<DFORMACION> DFORMACIONs { get; set; }
    }
}
