//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPISAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DDIRECCION
    {
        public string CEDULA { get; set; }
        public string CALLE { get; set; }
        public string EDIFICIO { get; set; }
        public string PISO { get; set; }
        public string NUMERO { get; set; }
        public string CIUDAD { get; set; }
        public string URBANIZACION { get; set; }
        public string COD_ESTADO { get; set; }
        public string COD_PAIS { get; set; }
        public string TELEFONOS { get; set; }
        public string COD_ESTADO_SSO { get; set; }
        public string COD_MUNICIPIO_SSO { get; set; }
        public string COD_PARROQUIA_SSO { get; set; }
        public string COD_USER_INS { get; set; }
        public System.DateTime FECHA_INS { get; set; }
        public string COD_USER_UPD { get; set; }
        public System.DateTime FECHA_UPD { get; set; }
    
        public virtual DPERSONALES DPERSONALE { get; set; }
        public virtual DUSUARIO DUSUARIO { get; set; }
        public virtual DUSUARIO DUSUARIO1 { get; set; }
        public virtual PAIS_ESTADO PAIS_ESTADO { get; set; }
        public virtual PARROQUIA_SSO PARROQUIA_SSO { get; set; }
    }
}
