//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPISAP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class DEXPERIENCIA
    {

        public string CEDULA { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_FIN { get; set; }
        public string EMPRESA { get; set; }
        public string CIUDAD { get; set; }
        public string PAIS { get; set; }
        public string COD_RAMO { get; set; }
        public string COD_ACTIVIDAD { get; set; }
        public string COD_RELACION { get; set; }
        public string COD_USER_INS { get; set; }
        public System.DateTime FECHA_INS { get; set; }
        public string COD_USER_UPD { get; set; }
        public System.DateTime FECHA_UPD { get; set; }
    
        public virtual ACTIVIDAD ACTIVIDAD { get; set; }
        public virtual DPERSONALES DPERSONALES { get; set; }
        public virtual DUSUARIO DUSUARIO { get; set; }
        public virtual DUSUARIO DUSUARIO1 { get; set; }
        public virtual PAIS PAISES { get; set; }
        public virtual RAMO RAMO { get; set; }
        public virtual RELACION_LABORAL RELACION_LABORAL { get; set; }
    }
}
