//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPISAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DFAMILIAR
    {
        public string CEDULA { get; set; }
        public string COD_PARENTESCO { get; set; }
        public string PRIMER_APELLIDO { get; set; }
        public string SEGUNDO_APELLIDO { get; set; }
        public string NOMBRES { get; set; }
        public System.DateTime FECHA_NACIMIENTO { get; set; }
        public string LUGAR_NACIMIENTO { get; set; }
        public string COD_PAIS { get; set; }
        public string COD_NACIONALIDAD { get; set; }
        public string CEDULA_FAMILIAR { get; set; }
        public string SEXO { get; set; }
        public string COD_USER_INS { get; set; }
        public System.DateTime FECHA_INS { get; set; }
        public string COD_USER_UPD { get; set; }
        public System.DateTime FECHA_UPD { get; set; }
        public decimal ID_FAMILIARES { get; set; }
    
        public virtual DPERSONALES DPERSONALE { get; set; }
        public virtual DUSUARIO DUSUARIO { get; set; }
        public virtual DUSUARIO DUSUARIO1 { get; set; }
        public virtual NACIONALIDAD NACIONALIDAD { get; set; }
        public virtual PAIS PAI { get; set; }
        public virtual PARENTESCO PARENTESCO { get; set; }
    }
}
