//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPISAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DPERSONALE
    {
        public DPERSONALE()
        {
            this.DCOMUNICACIONs = new HashSet<DCOMUNICACION>();
            this.DDISCAPACIDADs = new HashSet<DDISCAPACIDAD>();
            this.DEXPERIENCIAs = new HashSet<DEXPERIENCIA>();
            this.DFAMILIARES = new HashSet<DFAMILIARE>();
            this.DFORMACIONs = new HashSet<DFORMACION>();
        }
    
        public string FICHA { get; set; }
        public string CEDULA { get; set; }
        public string COD_SUCURSAL { get; set; }
        public string COD_GRUPO { get; set; }
        public string COD_AREA_PERSONAL { get; set; }
        public string CARGO { get; set; }
        public string TRATAMIENTO { get; set; }
        public string PRIMER_APELLIDO { get; set; }
        public string SEGUNDO_APELLIDO { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
        public string CIUDAD_NACIMIENTO { get; set; }
        public string COD_PAIS { get; set; }
        public string COD_ESTADO { get; set; }
        public string COD_NACIONALIDAD { get; set; }
        public string ESTADO_CIVIL { get; set; }
        public string SEXO { get; set; }
        public string RIF { get; set; }
        public string CALZADO { get; set; }
        public string CHEMISE { get; set; }
        public string PANTALON { get; set; }
        public string COD_USER_INS { get; set; }
        public System.DateTime FECHA_INS { get; set; }
        public string COD_USER_UPD { get; set; }
        public System.DateTime FECHA_UPD { get; set; }
    
        public virtual AREA_PERSONAL AREA_PERSONAL { get; set; }
        public virtual ICollection<DCOMUNICACION> DCOMUNICACIONs { get; set; }
        public virtual DCUENTA DCUENTA { get; set; }
        public virtual DDIRECCION DDIRECCION { get; set; }
        public virtual ICollection<DDISCAPACIDAD> DDISCAPACIDADs { get; set; }
        public virtual ICollection<DEXPERIENCIA> DEXPERIENCIAs { get; set; }
        public virtual ICollection<DFAMILIARE> DFAMILIARES { get; set; }
        public virtual ICollection<DFORMACION> DFORMACIONs { get; set; }
        public virtual DUSUARIO DUSUARIO { get; set; }
        public virtual DUSUARIO DUSUARIO1 { get; set; }
        public virtual GRUPO_PERSONAL GRUPO_PERSONAL { get; set; }
        public virtual NACIONALIDAD NACIONALIDAD { get; set; }
        public virtual PAIS_ESTADO PAIS_ESTADO { get; set; }
        public virtual SUCURSAL SUCURSAL { get; set; }
    }
}
