//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPISAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_SSO
    {
        public ESTADO_SSO()
        {
            this.MUNICIPIO_SSO = new HashSet<MUNICIPIO_SSO>();
        }
    
        public string COD_ESTADO_SSO { get; set; }
        public string DES_ESTADO_SSO { get; set; }
    
        public virtual ICollection<MUNICIPIO_SSO> MUNICIPIO_SSO { get; set; }
    }
}
