//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPISAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMACION
    {
        public FORMACION()
        {
            this.DFORMACIONs = new HashSet<DFORMACION>();
        }
    
        public string COD_FORMACION { get; set; }
        public string DES_FORMACION { get; set; }
    
        public virtual ICollection<DFORMACION> DFORMACIONs { get; set; }
    }
}
