//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPISAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRUPO_PERSONAL
    {
        public GRUPO_PERSONAL()
        {
            this.DPERSONALES = new HashSet<DPERSONALE>();
        }
    
        public string COD_GRUPO { get; set; }
        public string DES_GRUPO_PERSONAL { get; set; }
    
        public virtual ICollection<DPERSONALE> DPERSONALES { get; set; }
    }
}
