//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPISAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUNICIPIO_SSO
    {
        public MUNICIPIO_SSO()
        {
            this.PARROQUIA_SSO = new HashSet<PARROQUIA_SSO>();
        }
    
        public string COD_ESTADO_SSO { get; set; }
        public string COD_MUNICIPIO { get; set; }
        public string DES_MUNICIPIO { get; set; }
    
        public virtual ESTADO_SSO ESTADO_SSO { get; set; }
        public virtual ICollection<PARROQUIA_SSO> PARROQUIA_SSO { get; set; }
    }
}
