//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPISAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAI
    {
        public PAI()
        {
            this.DEXPERIENCIAs = new HashSet<DEXPERIENCIA>();
            this.DFAMILIARES = new HashSet<DFAMILIARE>();
            this.DFORMACIONs = new HashSet<DFORMACION>();
            this.PAIS_ESTADO = new HashSet<PAIS_ESTADO>();
        }
    
        public string COD_PAIS { get; set; }
        public string DES_PAIS { get; set; }
    
        public virtual ICollection<DEXPERIENCIA> DEXPERIENCIAs { get; set; }
        public virtual ICollection<DFAMILIARE> DFAMILIARES { get; set; }
        public virtual ICollection<DFORMACION> DFORMACIONs { get; set; }
        public virtual ICollection<PAIS_ESTADO> PAIS_ESTADO { get; set; }
    }
}
