//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPISAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAIS_ESTADO
    {
        public PAIS_ESTADO()
        {
            this.DDIRECCIONs = new HashSet<DDIRECCION>();
            this.DPERSONALES = new HashSet<DPERSONALES>();
        }
    
        public string COD_PAIS { get; set; }
        public string COD_ESTADO { get; set; }
        public string DES_ESTADO { get; set; }
    
        public virtual ICollection<DDIRECCION> DDIRECCIONs { get; set; }
        public virtual ICollection<DPERSONALES> DPERSONALES { get; set; }
        public virtual PAIS PAI { get; set; }
    }
}
