//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPISAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARROQUIA_SSO
    {
        public PARROQUIA_SSO()
        {
            this.DDIRECCIONs = new HashSet<DDIRECCION>();
        }
    
        public string COD_ESTADO { get; set; }
        public string COD_MUNICIPIO { get; set; }
        public string COD_PARROQUIA { get; set; }
        public string DES_PARROQUIA { get; set; }
    
        public virtual ICollection<DDIRECCION> DDIRECCIONs { get; set; }
        public virtual MUNICIPIO_SSO MUNICIPIO_SSO { get; set; }
    }
}
