//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPISAP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SPISAPEntities : DbContext
    {
        public SPISAPEntities()
            : base("name=SPISAPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACTIVIDAD> ACTIVIDADES { get; set; }
        public DbSet<AREA_PERSONAL> AREA_PERSONAL { get; set; }
        public DbSet<CLASE_ESPECIALIDAD> CLASE_ESPECIALIDAD { get; set; }
        public DbSet<CLASE_INSTITUTO> CLASE_INSTITUTO { get; set; }
        public DbSet<CLASE_TITULO> CLASE_TITULO { get; set; }
        public DbSet<DCOMUNICACION> DCOMUNICACIONES { get; set; }
        public DbSet<DCUENTA> DCUENTAS { get; set; }
        public DbSet<DDIRECCION> DDIRECCIONES { get; set; }
        public DbSet<DDISCAPACIDAD> DDISCAPACIDADES { get; set; }
        public DbSet<DPERSONALES> DPERSONALES { get; set; }
        public DbSet<DUSUARIO> DUSUARIOS { get; set; }
        public DbSet<ESTADO_SSO> ESTADO_SSO { get; set; }
        public DbSet<FORMACION> FORMACIONES { get; set; }
        public DbSet<GRUPO_PERSONAL> GRUPO_PERSONAL { get; set; }
        public DbSet<MUNICIPIO_SSO> MUNICIPIO_SSO { get; set; }
        public DbSet<NACIONALIDAD> NACIONALIDADES { get; set; }
        public DbSet<PAIS> PAISES { get; set; }
        public DbSet<PAIS_ESTADO> PAIS_ESTADO { get; set; }
        public DbSet<PARENTESCO> PARENTESCOS { get; set; }
        public DbSet<PARROQUIA_SSO> PARROQUIA_SSO { get; set; }
        public DbSet<RAMO> RAMOS { get; set; }
        public DbSet<RELACION_LABORAL> RELACION_LABORAL { get; set; }
        public DbSet<SUCURSAL> SUCURSALES { get; set; }
        public DbSet<DEXPERIENCIA> DEXPERIENCIAS { get; set; }
        public DbSet<DFAMILIAR> DFAMILIARES { get; set; }
        public DbSet<DFORMACION> DFORMACIONES { get; set; }
    }
}
