//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPISAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUCURSAL
    {
        public SUCURSAL()
        {
            this.DPERSONALES = new HashSet<DPERSONALES>();
            this.DUSUARIOS = new HashSet<DUSUARIO>();
        }
    
        public string COD_SUCURSAL { get; set; }
        public string DES_SUCURSAL { get; set; }
    
        public virtual ICollection<DPERSONALES> DPERSONALES { get; set; }
        public virtual ICollection<DUSUARIO> DUSUARIOS { get; set; }
    }
}
